import React from "react";

function Pick_number() {
  return (
    <div>
      <div className="single-pick">
        <div className="header-area">
          <h4 className="title">Pick 5 Numbers</h4>
          <div className="buttons">
            <a href="#" className="custom-button1">
              <i className="fa fa-magic"></i>Quick Pick
            </a>
            <a href="#" className="custom-button2">
              <i className="fa fa-trash"></i> Clear All
            </a>
          </div>
        </div>
        <div className="body-area">
          <ul>
            <li>
              <span>1</span>
            </li>
            <li>
              <span>2</span>
            </li>
            <li>
              <span>3</span>
            </li>
            <li>
              <span>4</span>
            </li>
            <li>
              <span>5</span>
            </li>
            <li>
              <span>6</span>
            </li>
            <li>
              <span>7</span>
            </li>
            <li>
              <span>8</span>
            </li>
            <li>
              <span>9</span>
            </li>
            <li>
              <span>10</span>
            </li>
            <li>
              <span>11</span>
            </li>
            <li>
              <span>12</span>
            </li>
            <li>
              <span>13</span>
            </li>
            <li>
              <span>14</span>
            </li>
            <li>
              <span>15</span>
            </li>
            <li>
              <span>16</span>
            </li>
            <li>
              <span>17</span>
            </li>
            <li>
              <span>18</span>
            </li>
            <li>
              <span>19</span>
            </li>
            <li>
              <span>20</span>
            </li>
            <li>
              <span>21</span>
            </li>
            <li>
              <span>22</span>
            </li>
            <li>
              <span>23</span>
            </li>
            <li>
              <span>24</span>
            </li>
            <li>
              <span>25</span>
            </li>
            <li>
              <span>26</span>
            </li>
            <li>
              <span>27</span>
            </li>
            <li>
              <span>28</span>
            </li>
            <li>
              <span>29</span>
            </li>
            <li>
              <span>30</span>
            </li>
            <li>
              <span>31</span>
            </li>
            <li>
              <span>32</span>
            </li>
            <li>
              <span>33</span>
            </li>
            <li>
              <span>34</span>
            </li>
            <li>
              <span>35</span>
            </li>
            <li>
              <span>36</span>
            </li>
            <li>
              <span>37</span>
            </li>
            <li>
              <span>38</span>
            </li>
            <li>
              <span>39</span>
            </li>
            <li>
              <span>40</span>
            </li>
          </ul>
          <div className="separator">
            <p>Pick 1 Power Ball</p>
          </div>
          <ul>
            <li>
              <span>1</span>
            </li>
            <li>
              <span>2</span>
            </li>
            <li>
              <span>3</span>
            </li>
            <li>
              <span>4</span>
            </li>
            <li>
              <span>5</span>
            </li>
            <li>
              <span>6</span>
            </li>
            <li>
              <span>7</span>
            </li>
            <li>
              <span>8</span>
            </li>
            <li>
              <span>9</span>
            </li>
            <li>
              <span>10</span>
            </li>
            <li>
              <span>11</span>
            </li>
            <li>
              <span>12</span>
            </li>
            <li>
              <span>13</span>
            </li>
            <li>
              <span>14</span>
            </li>
            <li>
              <span>15</span>
            </li>
            <li>
              <span>16</span>
            </li>
            <li>
              <span>17</span>
            </li>
            <li>
              <span>18</span>
            </li>
            <li>
              <span>19</span>
            </li>
            <li>
              <span>20</span>
            </li>
            <li>
              <span>21</span>
            </li>
            <li>
              <span>22</span>
            </li>
            <li>
              <span>23</span>
            </li>
            <li>
              <span>24</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export default Pick_number;
